version: '3.8'
services:
  backend:
    build: ./backend  # Path to backend Dockerfile
    ports:
      - "8000:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./backend:/app  # Mount local code for hot reload
      - /app/__pycache__  # Exclude pycache

  frontend:
    build: ./frontend  # Path to frontend Dockerfile
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/  # For container-to-container

    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount local code for hot reload
      - /app/node_modules  # Preserve node_modules

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: