# Generated by Django 5.1.6 on 2025-03-27 11:39

import django.db.models.deletion
import django.utils.timezone
import stock_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(default=stock_app.models.generate_unique_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_collection', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gain_or_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_active_status', models.BooleanField(default=True)),
                ('project_responsible_mail', models.EmailField(max_length=100)),
                ('project_opening_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_closing_dt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_authorizer_details', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invesment_investor_details', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_project_details', to='stock_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_investor_details', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_advisor_proj_details', to='stock_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trns_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=6)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trade_date', models.DateField(auto_now_add=True)),
                ('total_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_authorizer_details', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_instrument_details', to='stock_app.instrument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_project_details', to='stock_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='FinAdvisorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('com_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('accrued_dt', models.DateTimeField(auto_now_add=True)),
                ('disburse_st', models.BooleanField(default=False)),
                ('disburse_dt', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_advisor_com', to=settings.AUTH_USER_MODEL)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_authorizer_details', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_project', to='stock_app.project')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_trade_details', to='stock_app.trade')),
            ],
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribute_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gain_lose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_advisor', models.BooleanField(default=False)),
                ('disburse_st', models.BooleanField(default=False)),
                ('disburse_dt', models.DateTimeField(blank=True, null=True)),
                ('accr_dt', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_authorizer_details', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_investor_details', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_project_details', to='stock_app.project')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_trade_details', to='stock_app.trade')),
            ],
        ),
    ]
