# Generated by Django 5.1.6 on 2025-03-28 03:55

import uuid

import django.utils.timezone
from django.db import migrations, models

import stock_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_lose', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinAdvisorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('com_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('disburse_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribute_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disburse_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('accrued_dt', models.DateTimeField(auto_now_add=True)),
                ('disburse_st', models.BooleanField(default=False)),
                ('disburse_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(default=stock_app.models.generate_unique_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_collection', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gain_or_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('project_active_status', models.BooleanField(default=True)),
                ('project_responsible_mail', models.EmailField(max_length=100)),
                ('project_opening_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_closing_dt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trns_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=6)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trade_date', models.DateField(auto_now_add=True)),
                ('total_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
