# Generated by Django 5.1.6 on 2025-03-28 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finadvisorcommission',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_advisor_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finadvisorcommission',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialadvisor',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_investor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invesment_investor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorprofit',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_profit_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorprofit',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ben_investor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilt',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilt',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_project_details', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='investorprofit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_profit_project_details', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_project_details', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='financialadvisor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_advisor_proj_details', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='finadvisorcommission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_project', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_project_details', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='trade',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_instrument_details', to='stock_app.instrument'),
        ),
        migrations.AddField(
            model_name='trade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_project_details', to='stock_app.project'),
        ),
        migrations.AddField(
            model_name='profilt',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_trade_details', to='stock_app.trade'),
        ),
        migrations.AddField(
            model_name='investorprofit',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_profit_trade_details', to='stock_app.trade'),
        ),
        migrations.AddField(
            model_name='finadvisorcommission',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_trade_details', to='stock_app.trade'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_trade_details', to='stock_app.trade'),
        ),
    ]
