# Generated by Django 5.1.6 on 2025-03-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_rename_profilt_profit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorProfit',
        ),
    ]
