# Generated by Django 4.2.4 on 2025-01-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_financialadvisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='ait',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='howla',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='laga',
        ),
        migrations.AlterField(
            model_name='financialadvisor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_advisors', to='stock_app.project'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stock_app.project'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stock_app.project'),
        ),
    ]
