# Generated by Django 4.2.4 on 2025-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_remove_trade_ait_remove_trade_howla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='actual_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
