# Generated by Django 5.1.6 on 2025-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_investorprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofit',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
