# Generated by Django 4.2.4 on 2025-02-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_trade_actual_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
