# Generated by Django 4.2.4 on 2025-02-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_alter_trade_trade_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='face_value',
        ),
    ]
