# Generated by Django 5.1.6 on 2025-03-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_alter_project_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_collection',
            new_name='closing_balance',
        ),
        migrations.AddField(
            model_name='project',
            name='total_buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_sell',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
