# Generated by Django 4.2.4 on 2025-02-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_app', '0008_remove_instrument_face_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribute_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gain_lose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_advisor', models.BooleanField(default=False)),
                ('disburse_st', models.BooleanField(default=False)),
                ('trade_dt', models.DateField(auto_now=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_by_rec', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inst_rec', to='stock_app.instrument')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_rec', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_rec', to='stock_app.project')),
                ('trade_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.trade')),
            ],
        ),
    ]
