# Generated by Django 5.1.6 on 2025-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_rename_total_collection_project_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_sell_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
