# Generated by Django 4.2.4 on 2025-02-11 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_app', '0009_accountreceiable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountReceiable',
            new_name='AccountReceivable',
        ),
    ]
