# Generated by Django 4.2.4 on 2025-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0010_rename_accountreceiable_accountreceivable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountreceivable',
            old_name='trade_dt',
            new_name='accr_dt',
        ),
        migrations.RemoveField(
            model_name='accountreceivable',
            name='instrument',
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='disburse_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
