# Generated by Django 4.2.4 on 2025-02-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0011_rename_trade_dt_accountreceivable_accr_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountreceivable',
            name='trade_rec',
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trade_rec', to='stock_app.trade'),
            preserve_default=False,
        ),
    ]
