# Generated by Django 5.1.6 on 2025-02-23 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_remove_accountreceivable_trade_rec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreceivable',
            name='accr_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_investor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_project_details', to='stock_app.project'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_trade_details', to='stock_app.trade'),
        ),
        migrations.AlterField(
            model_name='financialadvisor',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_investor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialadvisor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_advisor_proj_details', to='stock_app.project'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invesment_investor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_project_details', to='stock_app.project'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_authorizer_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_instrument_details', to='stock_app.instrument'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_project_details', to='stock_app.project'),
        ),
    ]
