# Generated by Django 5.1.6 on 2025-03-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0014_project_project_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='project_active_status',
        ),
    ]
