# Generated by Django 5.1.6 on 2025-03-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0015_rename_project_status_project_project_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gain_or_lose',
            new_name='gain_or_loss',
        ),
    ]
