# Generated by Django 5.1.6 on 2025-03-22 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0016_rename_gain_or_lose_project_gain_or_loss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gain_or_loss',
            new_name='gain_or_lose',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_active_status',
            new_name='project_status',
        ),
        migrations.AddField(
            model_name='project',
            name='project_closing_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_opening_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='project_responsible_mail',
            field=models.EmailField(default='test@gmai.com', max_length=100),
            preserve_default=False,
        ),
    ]
