# Generated by Django 5.1.6 on 2025-03-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0017_rename_gain_or_loss_project_gain_or_lose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gain_or_lose',
            new_name='gain_or_loss',
        ),
    ]
