# Generated by Django 5.1.6 on 2025-03-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0018_rename_gain_or_lose_project_gain_or_loss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='project_active_status',
        ),
    ]
